### ISSUE TITLE
Indexed search functionality

### ISSUE THREAD

**Issue by markusjura** [lightbend/paradox#13]
It would be nice if paradox comes with a built-in indexed documentation search. The Lagom documentation is using [docsearch.js](https://github.com/algolia/docsearch) for it. With that, any documentation page is listed, incl. the sub section that contains the search term.

**Comment by jroper** [comment]
I don't think this is a paradox concern, the approach you mention requires raising a ticket with Algolia to get them to index the site.  Once that's done, you then include a snippet of javascript that they supply in the site.  Because of the manual step of raising a ticket with Algolia, there's simply no way paradox can include this out of the box, and usually that snippet would simply be included as part of a theme, and every paradox usage is going to use a somewhat customised theme anyway.

**Comment by markusjura** [comment]
Thanks for the info. Lets close the issue then.

**Comment by nafg** [comment]
It would be nice to do self-contained search with lunr. Ornate generates offline search.
