### ISSUE TITLE
Need PDF output

### ISSUE THREAD

**Issue by drewhk** [lightbend/paradox#14]
Many of our users/readers perfer to have a PDF version. We should have some options for this, maybe as simple as emitting LaTeX from the DOM.

**Comment by eed3si9n** [comment]
For Pamflet I've implemented PDF generation by creating a combined markdown, and then passing it to Pandoc. Looks like this - http://www.scala-sbt.org/0.13/docs/sbt-reference.pdf

**Comment by ktoso** [comment]
That would be good enough I think, looks pretty good.
In our community people keep praising the availability of PDF because they
often read the docs like a book.

-- 
Konrad Malawski

From: eugene yokota <notifications@github.com> <notifications@github.com>
Reply: lightbend/paradox
<reply@reply.github.com>
<reply@reply.github.com>
Date: 23 August 2016 at 18:46:47
To: lightbend/paradox <paradox@noreply.github.com>
<paradox@noreply.github.com>
Subject:  Re: [lightbend/paradox] Need PDF output (#14)

For Pamflet I've implemented PDF generation by creating a combined

**Comment by eed3si9n** [comment]
Yea. I think being able to download and carry docs around is a benefit of static generation in general. There are probably a few tweaks we want to allow in Paradox if we want to make combined markdown a thing, like not insisting on having h1 at the top of the page.

**Comment by raboof** [comment]
When groups are used ideally we'd be able to generate a PDF for each group

**Comment by dwijnand** [comment]
> When groups are used ideally we'd be able to generate a PDF for each group

groups?

**Comment by raboof** [comment]
http://developer.lightbend.com/docs/paradox/latest/features/groups.html :)

**Comment by raboof** [comment]
There are a number of ways to approach this, each with their pro's and cons. One is to take the generated HTML and post-process it. If anyone wants to give that a try, https://github.com/raboof/paradox-singlepage could be a starting point (though very incomplete and currently written towards processing the Akka docs)
