### ISSUE TITLE
Scaladoc links for Scala 2.11

### ISSUE THREAD

**Issue by netvl** [lightbend/paradox#190]
Apparently Paradox generates 2.12-compatible links for `@scaladoc` links. The project which I'm working on is a library for Spark jobs and, it is highly unlikely that it will ever be migrated from 2.11. I couldn't find in the documentation for Paradox how to change the format of Scaladoc links, and whether it is possible at all. If I understand correctly, this has been changed in [this PR](https://github.com/lightbend/paradox/pull/119), but I can't see there any possible way to tweak this behavior. How do I make Paradox generate the old format of links?

**Comment by ktoso** [comment]
Use an old version or contribute a fix :)

**Comment by netvl** [comment]
I would not mind contributing, just wanted to confirm if it is indeed not supported.

How do you think the decision of which format of links to use should be done? Should it depend on Scala version, like before? Or maybe a separate setting should be added?

**Comment by 2m** [comment]
I think by default it should depend on the Scala version. So the projects that use Paradox already do not need to change their builds when updating to the new version. That might be a good first step.

You can also add an override setting. But you can also leave it for future contributors when someone finds a need for it. :)

**Comment by jonas** [comment]
The motivation for the change was #104 which states that since Scala 2.10 scaladoc has supported "direct links" in addition to "index links"

Examples:
 - http://www.scala-lang.org/api/2.11.12/scala/collection/concurrent/TrieMap.html will open
   http://www.scala-lang.org/api/2.11.12/index.html#scala.collection.concurrent.TrieMap
 - http://www.scala-lang.org/api/2.10.6/scala/collection/concurrent/TrieMap.html will open
    http://www.scala-lang.org/api/2.10.6/index.html#scala.collection.concurrent.TrieMap
 - http://spark.apache.org/docs/2.0.0/api/scala/org/apache/spark/rdd/RDD.html (which uses Scala 2.11) will open 
    http://spark.apache.org/docs/2.0.0/api/scala/index.html#org.apache.spark.rdd.RDD

I don't know if this requires a special option when generating the Scaladoc, but I am curious why this is not supported in your library @netvl .

**Comment by netvl** [comment]
@jonas my assumption was that this was some kind of server setup which does the redirect. But I have just taken a look at my ghpages branch contents, and indeed there are HTML files for each class separately. I think the cause was that I have mistakenly thought that it is okay to use Scaladoc links to refer to nested classes, but apparently to refer to an inner class you need to write `Object$$Class` not `Object$.Class` (like you do in Scaladocs). I believe my problem is solved. Sorry for bothering!
