### ISSUE TITLE
Dependency tree integration

### ISSUE THREAD

**Issue by ennru** [lightbend/paradox#192]
An important part of a library is to communicate the dependencies it pulls in. 
For the Alpakka documentation, I'd like to pull in output from @jrudolph 's Dependency Graph plugin and integrate it with Paradox to show in the docs.

**Comment by ktoso** [comment]
Interesting, would you want to show the dependency tree in docs?

**Comment by ignasi35** [comment]
These can be rather big trees and in case of conflict rsolution varies depending on the build tool. Maybe a list of direct dependencies like [mvnrepository](https://mvnrepository.com/artifact/com.lightbend.akka/akka-stream-alpakka-cassandra_2.12/0.17) or [scaladex](https://index.scala-lang.org/akka/alpakka/akka-stream-alpakka-cassandra/0.17?target=_2.12) (low right menu) would be enough.

**Comment by jrudolph** [comment]
Using sbt-dependency-graph the simplest solution could work like this:

1. add sbt-dependency-graph plugin to the project
2. define some properties that expose output of dependency-graph tasks to paradox:

```
paradoxProperties ++= Map(
  "dependencyTree" -> (asciiTree in Compile).value,
  // there's no task like "asciiTree" that would just return the string without showing it for the dependencyList command
  "dependencyList" -> net.virtualvoid.sbt.graph.rendering.FlatList.render((moduleGraph in Compile).value, _.id.idString)
)
```

3. Use it in paradox

```
@@@vars

$dependencyList$

@@@
```

The output is not perfect as it contains the module itself and isn't formatted nicely. You would probably define your own method that takes the result of `moduleGraph` and render it as it fits.

So, instead, it would probably make sense to write a paradox directive with the expected behavior which also allows styling the text, e.g. to output a markdown table with the dependencies.

**Comment by ennru** [comment]
We've now created https://github.com/lightbend/sbt-paradox-dependencies to address this.

**Comment by ennru** [comment]
PR for linking to it is #277. 
Closing this as fixed.
