### ISSUE TITLE
paradoxTheme added to libraryDependencies

### ISSUE THREAD

**Issue by magro** [lightbend/paradox#225]
With [solrs](http://inoio.github.io/solrs/) I just started to use paradox - thanks for this awesome tool!

Now I realized, that this added the `paradoxTheme` to the `libraryDependecies` (see [ParadoxPlugin.scala#L54](https://github.com/lightbend/paradox/blame/master/plugin/src/main/scala/com/lightbend/paradox/sbt/ParadoxPlugin.scala#L54).
In consequence, this dependency is also written as dependency to the generated pom.xml on `publish`.

Appearently, a user of my library should not get the paradox theme as a transitive dependency.

This issue can be reproduced with `publishLocal` and inspecting the generated pom.xml.

Can this be fixed?

Note: this has already been asked in gitter [here](https://gitter.im/lightbend/paradox?at=5a90619de4ff28713aba3262), but was not answered AFAICS.

**Comment by eed3si9n** [comment]
Paradox is currently intended to work on a subproject on its own for docs.
Maybe that fact should be documented clearer. We can also try to move the theme out so a custom configuration.

**Comment by magro** [comment]
+1 for being more explicit on the assumed usage.

I wonder why the theme dependency is added at all - this was introduced in https://github.com/lightbend/paradox/commit/89d983874e35aea63d92416a88880cc269f65dcb, unfortunately the commit message does not mention the reason/motivation.

Not sure what it would mean to "move the theme out to a custom config" - can you give me some guidance so that I could submit a PR, or would you like to change it yourself?

**Comment by eed3si9n** [comment]
Paradox allows [theming](https://developer.lightbend.com/docs/paradox/current/features/theming.html), including reusing an existing theme published to some repo. That requires someone to resolve and download the theme, which is normally the job for library management like Ivy.

By "move the theme out to a custom config" I mean defining a hidden configuration, like ParadoxTheme and scoping the dependency to that, similar to the way Test configuration works.

https://github.com/lightbend/paradox/blob/4620d52884976326ecfbcc6ea8e6a8fa67b9164e/plugin/src/main/scala/com/lightbend/paradox/sbt/ParadoxPlugin.scala#L54

Since we are using sbt-web's mechanism to extract those assets, and it seems to be hardcoded for `Compile` configuration here https://github.com/sbt/sbt-web/blob/1c147d15c5bb39004b03f033e8a8de87c36a4b3c/src/main/scala/com/typesafe/sbt/web/SbtWeb.scala#L200, you'd need to recreate the mechanism to get the assets out of the custom configuration.

**Comment by magro** [comment]
Not sure I can follow - so the theme is added as library dependency so that it's in the classpath for sbt-web, so that sbt-web can extract the files from the theme jar?

I just tried to add the `paradoxTheme` to `libraryDependencies` in some new scope, and this seems to fix my issue, and the documentation can still be generated as expected. Not sure why sbt-web can still extract files from the theme jar, but to me this seems to be a valid fix/solution. WDYT?
