### ISSUE TITLE
Snips included with @@snip introduce extra indentation

### ISSUE THREAD

**Issue by jrudolph** [lightbend/paradox#84]
Seems this problem was introduced with 0.2.8.

![screenshot from 2017-01-10 16 27 38](https://cloud.githubusercontent.com/assets/9868/21812007/e404268a-d751-11e6-998b-41bedb095fda.png)

**Comment by ktoso** [comment]
To reproduce: 

```
git clone https://github.com/akka/akka-http
sbt shell 
  project docs
  paradox
```

**Comment by jrudolph** [comment]
Seems the generated source code is introducing the indent:

```
                <pre class="prettyprint"><code class="language-scala">import akka.actor.{ActorRef, ActorSystem}
                import akka.http.scaladsl.coding.Deflate
                import akka.http.scaladsl.marshalling.ToResponseMarshaller
                import akka.http.scaladsl.model.StatusCodes.MovedPermanently
                import akka.http.scaladsl.server.Directives._
                import akka.http.scaladsl.unmarshalling.FromRequestUnmarshaller
                import akka.pattern.ask
                import akka.stream.ActorMaterializer
                import akka.util.Timeout

                </pre>
```

**Comment by jrudolph** [comment]
Turned out, this hasn't anything to do with the new version, but we changed the page template and added indentation before `$page.content$`. It seems this prompted the template engine to indent all included lines as well. It doesn't seem particular smart for an HTML template to add indentation to `<pre>` blocks. Is it possible to change that behavior?

**Comment by gsechaud** [comment]
I have looked at the problem and it seems that the "pre" tag indent bug comes from pegdown (not sure about it) then it would not be possible to fix this directly in paradox, but it is possible to change the javascript file for the template in order to remove the indent in the "pre" tags but then it would just be applied to the default paradox template (that you are using). This can be a temporary solution but it would be good to fix this at a higher level as well.

![screenshot from 2017-01-11 10 43 12](https://cloud.githubusercontent.com/assets/6824579/21845062/60257828-d7f1-11e6-9c24-56f4ffa0dc94.png)

the javascript file change in the template would work for your example but not sure if this is the expected result for the following:

![screenshot from 2017-01-11 10 47 40](https://cloud.githubusercontent.com/assets/6824579/21845078/7785263a-d7f1-11e6-97e3-b8ea46a964d7.png)

**Comment by jrudolph** [comment]
I think it comes from ST4. Not indenting `$page.contents$` fixed it for us. See https://github.com/akka/akka-http/pull/747/files

**Comment by ktoso** [comment]
I see, that's why it worked on paraox xince the template does not indent anything at all: https://github.com/lightbend/paradox/blob/master/themes/generic/src/main/assets/page.st
Great find, thanks.


On 11 January 2017 at 11:44:02, gsechaud (notifications@github.com) wrote:

I have looked at the problem and it seems that the "pre" tag indent bug comes from pegdown (not sure about it) then it would not be possible to fix this directly in paradox, but it is possible to change the javascript file for the template in order to remove the indent in the "pre" tags but then it would just be applied to the default paradox template (that you are using). This can be a temporary solution but it would be good to fix this at a higher level as well.



the javascript file change in the template would work for your example but not sure if this is the expected result for the following:
