### ISSUE TITLE
Can't use variable templating in markdown

### ISSUE THREAD

**Issue by Sciss** [lightbend/paradox#92]
According to the docs, this should be possible:

In `build.sbt`:

    paradoxProperties in Compile ++= Map(
      "image.base_url" -> "assets/images",
      "foo" -> """<span class="special">bar</span>"""
    )

In `test.md`:

    $foo$ should read bar with special CSS.

But it simply renders `$foo$` instead of `bar` inside a `<SPAN>`.

Or am I doing something wrong?

**Comment by gsechaud** [comment]
Try to use `@var[foo]` instead, the `$` support in markdown files will be introduced in release 0.2.9 thanks to https://github.com/lightbend/paradox/pull/85.

**Comment by Sciss** [comment]
Excellent, thanks! May I use this opportunity to ask if the md processor supports syntax for annotating with a span-class? (I know you provide special directive for div-classes)

**Comment by gsechaud** [comment]
No for now, only the div block is supported: http://developer.lightbend.com/docs/paradox/latest/features/css-friendliness.html

For now, you could use the div support and change it in your css file in order to make it work as a span tag. But that might be a good thing to include this new feature in a new release of course.
